# Generated by Django 6.0.6 on 2026-07-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_exercise_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
