# Generated by Django 6.0.6 on 2026-07-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_exercise_rest_time_exercise_sets_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobility_legs", "Mobilidade - Pernas"),
                    ("mobility_arms", "Mobilidade - Braços"),
                    ("mobility_trunk", "Mobilidade - Tronco"),
                    ("warmup", "Aquecimento"),
                    ("legs", "Fortalecimento - Pernas"),
                    ("arms", "Fortalecimento - Braços"),
                    ("trunk", "Fortalecimento - Tronco"),
                    ("stretching", "Alongamento"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
