# Generated by Django 6.0.6 on 2026-07-11 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_training_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailypainreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="dailypainreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
