# Generated by Django 6.0.6 on 2026-07-11 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_dailypainreport_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyfatiguereport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dailysleepreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dailyswellingreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="dailyfatiguereport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailysleepreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailysleepreport",
            name="sleep_level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyswellingreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyfatiguereport",
            name="fatigue_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dailysleepreport",
            name="sleep_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailysleepreport",
            name="sleep_quality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
